# Generated by Django 2.2.1 on 2019-05-28 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('-', '-')], default='-', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='height',
            field=models.FloatField(default=0.0),
        ),
    ]
