# Generated by Django 2.2.1 on 2019-05-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='goal',
            field=models.IntegerField(default=0),
        ),
    ]
