# Generated by Django 2.2.1 on 2019-05-29 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_ingredient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
